---
# Bootstrap permission for joining the cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karpenter-node-bootstrap
roleRef:
  kind: ClusterRole
  name: system:node-bootstrapper
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: system:bootstrappers
    apiGroup: rbac.authorization.k8s.io

---
# Full system:node permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karpenter-nodes
roleRef:
  kind: ClusterRole
  name: system:node
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: system:nodes
    apiGroup: rbac.authorization.k8s.io


# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: karpenter-node-role-binding
# roleRef:
#   kind: ClusterRole
#   name: system:node
#   apiGroup: rbac.authorization.k8s.io
# subjects:
#   - kind: User
#     name: arn:aws:sts::884360309640:assumed-role/KarpenterNodeRole-arc-poc-debash/i-086757657768686ac
#     apiGroup: rbac.authorization.k8s.io
#   - kind: User
#     name: arn:aws:sts::884360309640:assumed-role/KarpenterNodeRole-arc-poc-debash/i-07878998797987987
#     apiGroup: rbac.authorization.k8s.io
