---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: general
spec:
  metadataOptions:
    httpPutResponseHopLimit: 2
  amiFamily: AL2
  instanceProfile: KarpenterNodeInstanceProfile-arc-poc-cluster
  subnetSelectorTerms:
    - tags:
        "karpenter.sh/discovery": arc-poc-cluster                # Replace with the EKS cluster name
  securityGroupSelectorTerms:
    - tags:
        "karpenter.sh/discovery": arc-poc-cluster
  tags:
    Name: karpenter-node
