---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: general
spec:
  metadataOptions:
    httpPutResponseHopLimit: 2
  amiFamily: AL2
  instanceProfile: KarpenterNodeInstanceProfile-<cluster_name>
  subnetSelectorTerms:
    - tags:
        "karpenter.sh/discovery": <cluster_name>                # Replace with the EKS cluster name
  securityGroupSelectorTerms:
    - tags:
        "karpenter.sh/discovery": <cluster_name>
  tags:
    Name: karpenter-node
