---
name: Code approval

on: pull_request_review


jobs:
  labelWhenApproved:
    runs-on:
      - self-hosted
      - refarch
    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
